image:
  repository: gcr.io/spankchain-camsite-prod/github-spankchain-camsite/vynos
ingress:
  enabled: true
  hosts:
    - vynos.spankchain.com
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: spankchain-ssl
      hosts:
        - vynos.spankchain.com

resources:
  limits:
    cpu: 4
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 150Mi
